modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
issueTrackerURL="https://github.com/TheKiritoPlayer20/SuperTools/issues"

[[mods]]
modId="supertools"
version="${file.jarVersion}"
displayName="Super Tools"
updateJSONURL="https://raw.githubusercontent.com/TheKiritoPlayer20/SuperTools/updates/update.json"
logoFile="supertools_logo.png"


credits="Textures by: TheLuigiplayer, Code by: KG20"
authors="KG20 & TheLuigiplayer"
description='''
The SuperTools Mod. It adds Lapis, Redstone, Quartz, Emerald, Obsidian & Copper Tools and also Emerald, Quartz, Lapis,
Obsidian & Copper Armor. But the special things are the Super Tools, like the Pickaxe, Shovel, Axe or Hoe which have a 3x3 working area.
The Sword gives the target you hit with it a potion effect like the Cup and the Special Cup. Made by TheLuigiplayer & KG20 Disclaimer:
Make sure to download this mod from Curseforge or Planetminecraft.
'''


[[dependencies.supertools]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[43,)" #mandatory
    ordering="NONE"
    side="BOTH"


[[dependencies.supertools]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"